### PR TITLE
feat: merge dev into main

### PR DESCRIPTION
**Pull request by jvondermarck**
It would be great to merge all the code from dev to the main production branch and make a [release tag version](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

### CODE REVIEW

**Comment by joe67100** [comment]
No

**Comment by jvondermarck** [comment]
asking
PLEASE

**Comment by joe67100** [comment]
If you become a collaborator to this project and termine toutes les tâches qu'il faut finish

**Comment by jvondermarck** [comment]
> If you become a collaborator to this project and termine toutes les tâches qu'il faut finish

I will maybe dare to finish everything !

**Comment by bastianfbr** [comment]
Maybe we could merge in main for each big feature

**Comment by joe67100** [comment]
Maybe we could quoicoubeh

**Comment by jvondermarck** [comment]
I am still waiting...

**Comment by jvondermarck** [comment]
WaitingWaitingPatientlyGIF

**Comment by joe67100** [comment]
lâche ça, ça va pas merge

**Comment by jvondermarck** [comment]
@joe67100 blame.

**Comment by jvondermarck** [comment]
alors ?

**Comment by jvondermarck** [comment]
on étudie pas la PR des copains ?

**Pull request closed without merging**
